# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('passwd', models.TextField()),
                ('organization', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
