# Generated by Django 2.0.2 on 2018-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170802_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='bm_fish_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=2)),
                ('district_code', models.CharField(max_length=15)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
